import { Inter } from "next/font/google";
import "./globals.css";
import { MainNavbar } from "@/components/navbar";


const latin = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href="/image/logo.png" type="image/png" />
      <body className={`max-w-screen-2xl mx-auto ${latin.className}`}>
        <MainNavbar />
        {children}
      </body>
    </html>
  );
}
